### ISSUE TITLE
gert_token - Refresh Token missing 

### ISSUE THREAD

**Issue by squidswc** [microsoftgraph/msgraph-training-pythondjangoapp#10]
On expiration the get_token function gets an error: 

> (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_token'.

Appears the token doesn't carry this field at all? @jasonjoh

**Comment by jasonjoh** [comment]
I'll take a look when I can, but that's not expected. There should be a refresh token. Are you including the `offline_access` scope in `oauth_settings.yml`?

**Comment by squidswc** [comment]
Thanks for your reply Jason. 

I actually managed to identify the issue as the url I was using so no action necessary (and apologies - i should've closed the request)

Cheers,
Craig.

⁣P: 0447098770
E: craig.scott@swcompliance.com.au
W: www.swcompliance.com.au​

**Comment by jasonjoh** [comment]
No problem. Glad you got it sorted out.
