### ISSUE TITLE
MissingTokenError

### ISSUE THREAD

**Issue by BosnaZmaj** [microsoftgraph/msgraph-training-pythondjangoapp#12]
I am getting the error (missing_token) Missing access token parameter. It is related to the file auth_helper specifically `token = aad_auth.fetch_token(token_url,
        client_secret = settings['app_secret'],
        authorization_response=callback_url)`

I couldn't find anything related to this on web

When running the completed project from here I find no issues. Any idea?

**Comment by jasonjoh** [comment]
Have you diff'ed the working and non-working projects? Are they using the same app ID/secret? I haven't encountered that error, but it sounds like it's coming from the Requests-OAuthlib library and probably indicates an issue with the response from the token request.

**Comment by jasonjoh** [comment]
I wonder if it's a version issue with that library. I see an issue on their GitHub repository: https://github.com/requests/requests-oauthlib/issues/324. Some users report downgrading the library fixes the problem for them.

The completed project uses 1.0.0, but I see the latest version is 1.1.0. You probably got the latest if you went through the tutorial steps.

**Comment by BosnaZmaj** [comment]
@jasonjoh 
You are correct. It was the requests-oauthlib library. Downgrading from 1.1 to 1.0 fixed the issue. Thanks for the response.

**Comment by jasonjoh** [comment]
No problem. I'm going to dig in and see if I can figure out how to make it work with the latest, but glad you're unblocked.

**Comment by jasonjoh** [comment]
Hmm interesting. I just updated the library and ran the project, and it's working without any changes. Do you happen to remember what version you had installed before downgrading?

**Comment by BosnaZmaj** [comment]
It was the default found on pip. To be honest I forgot the version number.
