### ISSUE TITLE
POST Send Email Python Django

### ISSUE THREAD

**Issue by lcgosi** [microsoftgraph/msgraph-training-pythondjangoapp#19]
I am pretty new in python and ms graph and i am trying to create a page to send email through django, but I was unsuccessful.
return http 403.

#From outlookservices.py
def send_email(access_token):
  send_email_url = graph_endpoint.format('/me/sendMail') # /me/messages/{id}/send
  payload = {'Message': {'Subject': subject,
                             'Body': {'ContentType': content_type, 'Content': body},
                             'ToRecipients': recipient_list,
                             'Attachments': attached_files},
                 'SaveToSentItems': 'true'}

  r = make_api_call('POST', send_email_url, access_token, payload)
  if (r.status_code == requests.codes.ok):
    print("OK")
    return r.json()
  else:
    print(r)
    return "{0}: {1}".format(r.status_code, r.text) 

#views.py
def sendemail(request):
  access_token = get_access_token(request, request.build_absolute_uri(reverse('app:gettoken')))
  if not access_token:
    print("not token")
    return HttpResponseRedirect(reverse('app:home'))
  else:
    print("token")
    messages = send_email(access_token)
    context = { 'messages': messages }
    return render(request, 'pages/sendemail.html', context) 

could you help me with anyidea?
on the web e on the official documentation i just can find GET methods examples.

thanks a lot
Sorry if I am asking in a wrong place.

**Comment by jasonjoh** [comment]
It sounds like you do not have the required permission scope in your token. You need `Mail.Send`, and this sample only uses `User.Read` and `Calendars.Read`.

**Comment by lcgosi** [comment]
ahh I see... I am gonna try to change this so!
Thanks a lot for your attention and help =)

**Comment by lcgosi** [comment]
Hey, just come back here to say thanks... i changed my permissions and i received the email!
Thanks again!
