### ISSUE TITLE
Quotes Needed on YAML Values

### ISSUE THREAD

**Issue by msisson** [microsoftgraph/msgraph-training-pythondjangoapp#20]
When the app_secret, or any other config values, end with a colon you get this error when trying to generate the database:

C:\GraphPython\graph_tutorial>python manage.py migrate
yaml.scanner.ScannerError: mapping values are not allowed here
  in "oauth_settings.yml", line 2, column 35

All values in the oauth_settings.yml file should have strings around them. This fixes the problem.

**Comment by jasonjoh** [comment]
Good catch! I'll get that into the next update.
