### ISSUE TITLE
AADSTS50011

### ISSUE THREAD

**Issue by david-f** [microsoftgraph/msgraph-training-pythondjangoapp#21]
Have followed the tutorial but am receiving the AADSTS50011 error, i.e. : The reply url specified in the request does not match the reply urls configured for the application: 'xxxx'. It is very hard to debug this when I cannot find the "reply url specified in the request". The logs in the AAD admin center do record my failed attempts to log-in but they do not appear to contain the reply url that causes the error. How can I find what AAD receives?

My setup has Nginx, Gunicorn fronting Django running on OSX.

Thanks for any help.

**Comment by jasonjoh** [comment]
When the app redirects away to login.microsoftonline.com, you can copy the URL and look at the query parameters. One of those will be the `redirect_uri`. That should match what you configured in the app registration.

**Comment by david-f** [comment]
Thank-you Jason, that helped me fix the problem.
