### ISSUE TITLE
POST requests?

### ISSUE THREAD

**Issue by david-f** [microsoftgraph/msgraph-training-pythondjangoapp#22]
I have been able to successfully run the tutorial code with GET requests. Now I wish to make POST requests with a graph_client.post(https://graph.microsoft.com/v1.0/users, data={'userPrincipalName': 'sue@example.com', etc... }) type of construction. Unfortunately this   generates a HTTP 400 message of the form 'code': 'BadRequest', 'message': 'Entity only allows writes with a JSON Content-Type header.'. Will the tutorial constructs work with POST requests?
Thanks!
David

=====
Update.
I was able to resolve my issue by using post requests that include an explicit Content-Type header, like so:

graph_client.post(cmd[1], data=json.dumps(ext_cmd[1]),
                               headers={"Content-Type": "application/json"})

I now consider this issue to be closed.
Thanks.

**Comment by vikrant10** [comment]
Hi David,
can you please share the code you solved. I have been tucked at the same point where you were stuck. And it's hard for me to understand below lines suggested by you

graph_client.post(cmd[1], data=json.dumps(ext_cmd[1]),
headers={"Content-Type": "application/json"})

If you can possible send me a screenshot of the code where these above lines are meant to be written, then it will be a great help, I will be grateful to you.

**Comment by vikrant10** [comment]
If you can guide me on where to add the lines to make a POST method work successfully. I am attaching screenshots of my code please find below

HTML page:-
![1](https://user-images.githubusercontent.com/32262306/78780464-4532ef80-79bc-11ea-87e1-eb4bed92429b.PNG)

views.py:-
![2](https://user-images.githubusercontent.com/32262306/78780490-511eb180-79bc-11ea-8ca7-80ea75469978.PNG)

graph_helper.py:-
![3](https://user-images.githubusercontent.com/32262306/78780522-6398eb00-79bc-11ea-84bb-d69a05037de0.PNG)
