### ISSUE TITLE
May need to import render

### ISSUE THREAD

**Issue by ShinyaFukumura** [microsoftgraph/msgraph-training-pythondjangoapp#24]
I've tried a tutorial "Build Python Django apps with Microsoft Graph".
Then I found that I needed an additional code at last section in step "Create a Python Django web app".

I added a below line in top of ./tutorial/views.py .

```
from django.shortcuts import render
```

If needed please confirm this.

Thank you for your great tutorial.

**Comment by jasonjoh** [comment]
Yes, that is required. Thanks for reporting, I'll get this fixed.
