### ISSUE TITLE
Error while trying to read emails

### ISSUE THREAD

**Issue by tejabhanu03** [microsoftgraph/msgraph-training-pythondjangoapp#29]
{'error': {'code': 'ErrorAccessDenied', 'message': 'Access is denied. Check credentials and try again.', 'innerError': {'request-id': 'd6803fce-e258-4627-bc8d-f0ab25c84a94', 'date': '2020-01-09T06:05:28'}}}

I am getting above response when I add a method get_email_events(token) in graph_helper.py. please help.

method implementation in tutorial/graph_helper.py

def get_email_events(token):
  graph_client = OAuth2Session(token=token)
  print(str(graph_client)+" in email")
  query_params = {
    '$filter':"importance eq 'high'"
  }
  # Send GET to /me/events
  events = graph_client.get('{0}/me/events'.format(graph_url), params=query_params)  # Return the JSON result
  # print(events.json())
  return events.json()

**Comment by jasonjoh** [comment]
A few things you can check:

- Get your access token and parse it with the https://jwt.ms tool to confirm that it is the correct identity and that the `scp` claim contains `Calendars.Read`.
- Try making the same query with [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) with the same account.
