### ISSUE TITLE
App registration does not match guide

### ISSUE THREAD

**Issue by Krogsager** [microsoftgraph/msgraph-training-pythondjangoapp#3]
The guide does not specify type and URL. What is needed to complete the tutorial?
![image](https://user-images.githubusercontent.com/27994384/47997580-9cb09a00-e0fc-11e8-8109-60d58f29d598.png)

**Comment by Krogsager** [comment]
It was a bit of both. I am at https://apps.dev.microsoft.com/ but have two "Add an app" buttons. It looks like a UI error, but one was for azure and the other for 'converged applications'

**Comment by jasonjoh** [comment]
Ah yeah, that will make a difference. I tried to call that out with a note in the walkthrough. The Azure team is working on the app registration experience so hopefully it will be a little smoother in the future.
