### ISSUE TITLE
The term 'python' is not recognized

### ISSUE THREAD

**Issue by nickg33** [microsoftgraph/msgraph-training-pythondjangoapp#30]
https://developer.microsoft.com/en-us/graph/quick-start?appID=9b019258-e2d4-4800-8d5d-6368482e027b&appName=My%20Python%20App&redirectUrl=http://localhost:8000/tutorial/callback&platform=option-Python

On running the code the following error is encountered:

python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python manage.py migrate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by nickg33** [comment]
This can be remedied by calling py rather than python.

e.g. _py manage,py migrate_ rather than _python manage.py migrate_

**Comment by jasonjoh** [comment]
I suspect this depends on your system configuration. As I recall there was an option to add Python to your PATH when installing it on Windows, which should have made "python" work for you.
