### ISSUE TITLE
Auto-Generated Quickstart fails with Python 2.7.17 pip 9.0.1 on WSL

### ISSUE THREAD

**Issue by ShaneC** [microsoftgraph/msgraph-training-pythondjangoapp#35]
Microsoft Graph Quick Start - Python ([link](https://developer.microsoft.com/en-us/graph/quick-start?platform=option-Python))

**Expected:** pip command on un-modified generated requirements.txt installs 

**Actual:** pip command fails with error message
`Collecting asgiref==3.2.7 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement asgiref==3.2.7 (from -r requirements.txt (line 1)) (from versions: 0.8, 0.9, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.2, 0.13.3, 0.14.0, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0, 3.2.1, 3.2.2, 3.2.3)
No matching distribution found for asgiref==3.2.7 (from -r requirements.txt (line 1))`

**Repro Steps:**
1. Go to Python Quick Start, complete steps 1 (Python select) and 2 (App ID registration)
2. Return back to MS Graph developer portal, enter client secret value for quick start app
3. Confirm "Registration Successful!", move on to "Step 3: Start coding"
4. Click download button for "Download the REST-based code sample"
5. Download and unzip the file (Windows platform)
6. In WSL (Windows Subsystem for Linux) environment, Ubuntu shell within Windows Terminal, navigate to the extracted folder (msgraph-training-pythondjangoapp)
7. Confirm python and python-pip are installed (Python 2.7.17, pip 9.0.1)
8. Run `pip install -r requirements.txt`
9. Receive error listed above
10. Attempt in sudo, just to be sure
11. Receive same error listed above

**Comment by jasonjoh** [comment]
@ShaneC there should be a version file in that zip - can you tell me what version number is in it?

**Comment by jasonjoh** [comment]
That's an odd error given that 3.2.7 is definitely available: https://pypi.org/project/asgiref/. It's the first entry in requirements.txt - I wonder if it's just failing there and stopping. Can you try `pip install Django==3.0.4` and see if that succeeds?

**Comment by ShaneC** [comment]
Thanks @jasonjoh -- The version in the zip is 1.2. 

Your suspicion may be correct, the same issue happens with the Django install:

`user@box:/mnt/c/Users/schism/Desktop/msgraph-training-pythondjangoapp/graph_tutorial$ pip install Django==3.0.4
Collecting Django==3.0.4
  Could not find a version that satisfies the requirement Django==3.0.4 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29)
No matching distribution found for Django==3.0.4`

Maybe a WSL issue? I just tried this same zipfile on the same Windows box within PowerShell and executed the commands on the Windows Python installation (as opposed to WSL instance), and it worked perfectly. 

I'll do some more debugging and then forward to those folks.

**Comment by jasonjoh** [comment]
maybe, or some subtle difference in Python on Linux vs Windows. I wonder if you can point pip at different repositories, and it's just misconfigured?

**Comment by jasonjoh** [comment]
https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies maybe?

**Comment by ShaneC** [comment]
I followed that guide, and also explicitly upgraded both python and python-pip, no dice. I did figure it out though (and it exposes my newbie-ness with Python on Ubuntu/WSL):

The packages required for this require Python 3. On Ubuntu, python and pip commands default to Python 2. You need to invoke `pip3 install -r requirements.txt`. Using that it worked.

The takeaway, for the apparent novices like myself, it may be helpful to update the Graph documentation to specify in the instructions (Use pip3 command on Linux or WSL platforms).

So, perhaps, instead of:
`Run this command to install the required Python package dependencies: pip install -r requirements.txt.`

Changing to:
`Run this command to install the required Python package dependencies: pip install -r requirements.txt. (For Ubuntu and Linux distributions, you may need to invoke pip3 install -r requirements.txt to run using Python 3)`

**Comment by jasonjoh** [comment]
I'll work with the portal team to get the instruction on the quick-start page updated.

**Comment by ries9112** [comment]
I ran into the same issue as described by @ShaneC and this thread was helpful. I agree it would be helpful to specify Python 3 in the error message, but I wouldn't keep it specific to Ubuntu and Linux since I am having the same issue on MacOS (with M1 chip).

I also wanted to add that the subsequent commands from the quickstart also need to be run using Python 3. See screenshots below of the error when using Python 2.7:
![image](https://user-images.githubusercontent.com/32306488/104666624-8f56a900-5691-11eb-960f-21b63cc50df4.png)

![image](https://user-images.githubusercontent.com/32306488/104666643-9b426b00-5691-11eb-9d51-0325f560f992.png)

But these commands work fine when using python3:
![image](https://user-images.githubusercontent.com/32306488/104666803-fffdc580-5691-11eb-9925-62c53e05720c.png)

**Comment by jasonjoh** [comment]
Thanks for the report @ries9112. If you run `python --version`, I'm guessing it reports a 2.x version? It might be enough to add to the tutorial at the beginning to run that, and if it reports 2.x, use the `python3` command.

`python3` doesn't seem to be universal: on my Windows 10 machine with only Python 3.9, running python3 gives an error about installing Python from the Microsoft Store!?

```
▶ python3 --version
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```

**Comment by jasonjoh** [comment]
Closing as we've greatly simplified the downloadable quickstart, and it's no longer based on this project.
