### ISSUE TITLE
Any plans on upgrading the tutorial to the new auth API ?

### ISSUE THREAD

**Issue by Noezor** [microsoftgraph/msgraph-training-pythondjangoapp#38]
According to [this post](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363), the authentification method used in this tutorial is not up to date. Any plans on moving ?

**Comment by jasonjoh** [comment]
While this tutorial doesn't use MSAL for Python, it does use the same auth method (using the Microsoft identity platform v2 endpoints). But yes, it is planned to update this tutorial to use MSAL - should be done by end of year at latest.

**Comment by jasonjoh** [comment]
Fixed in #40
