### ISSUE TITLE
Sign in does not work

### ISSUE THREAD

**Issue by PiktasDede** [microsoftgraph/msgraph-training-pythondjangoapp#42]
### Where did you get the code?

- [x] Downloaded from GitHub
- [x] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

When you click sign in you get an error The input scopes should be a list, tuple, or set

### To Reproduce

1. Go to 'main page'
1. Click on 'sign in'
1. See error

### Expected behavior

It should give you prompt to authenticate you with Microsoft account

### Screenshots

![image](https://user-images.githubusercontent.com/76781250/103356463-a0ac8c80-4ab9-11eb-81d4-ed9e63d44a75.png)

**Comment by jasonjoh** [comment]
What does your oauth_settings.yml file look like (without sharing the `app_secret`)?

**Comment by PiktasDede** [comment]
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read"
authority: "https://login.microsoftonline.com/db104ae2-fb40-4cc2-8589-b52787e96983"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"

I tried to change exactly as it was in tutorial even downloaded code from git still same issue

**Comment by jasonjoh** [comment]
Hmm. The error indicates that the scopes passed in aren't valid, which makes me think there's something going wrong when loading the YAML file. In auth_helper.py, can you check the value of `settings` after the `settings = yaml.load(stream, yaml.SafeLoader)` line? Just add `print(settings)` should do it. The `scopes` value should be a list, like:

```
'scopes': ['user.read', 'mailboxsettings.read', 'calendars.readwrite']
```

What version of msal and PyYAML do you have installed?

**Comment by PiktasDede** [comment]
PyYAML==5.3.1
msal==1.8.0

**Comment by jasonjoh** [comment]
You do use a newer MSAL version, but I just updated here and still don't hit this problem. Did you add the `print(settings)` line? Assuming you did, and the value looks right, you should report this on the [msal repo](https://github.com/AzureAD/microsoft-authentication-library-for-python). The error is happening in their code.
