### ISSUE TITLE
Not pulling calendar events

### ISSUE THREAD

**Issue by bjornpoort** [microsoftgraph/msgraph-training-pythondjangoapp#45]
### Where did you get the code?

- [x ] Downloaded from GitHub
- [x ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

I ran the GitHub version and the tutorial version. Was able to post a new event successfully, but couldn't output any calendar events.

I had the former version of the tutorial installed this morning and that did pull the calendar events.

### To Reproduce

1. Go to calendar
1. Click on '....'
1. Scroll down to '....'
1. See error

### Desktop

- OS: iOs
- Browser safari

### Dependency versions

- Authentication library (MSAL, etc.) version: as per tutorial
- Graph library (Graph SDK, REST library, etc.) version: as per tutorial

### Additional context

printed the events:

{'@odata.context': "https://graph.microsoft.com/v1.0/$metadata#users('---')/calendarView(subject,organizer,start,end)", 'value': []}

**Comment by jasonjoh** [comment]
@bjornpoort one difference between this and the old tutorial is how the events are requested. The new version limits the events to any on the calendar in the current week. Can you confirm that your calendar has events in the current week?

If so, then it would be good to figure out what request is being made, and to try it in Graph Explorer to see if it reproduces the problem.

**Comment by bjornpoort** [comment]
Thank you Jason for responding. That resolves it, I missed that.  It was really that trivial. Great work on this tutorial btw!

**Comment by jasonjoh** [comment]
Sweet! Glad it was something simple. Thanks for the positive feedback, always nice to hear!
