### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by samwelkanda** [microsoftgraph/msgraph-training-pythondjangoapp#48]
### Where did you get the code?

Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

There is a typo in the documentation that refers to a non-existent function, `get_sign_in_url` leading to unnecessary `ImportError`.
```py
from tutorial.auth_helper import get_sign_in_url, get_token_from_code, store_user, remove_user_and_token, get_token
```
### To Reproduce

1. Go to 'Python tutorial main page'
2. Click on 'Step 3: Add Azure AD authentication'
3. Scroll down to 'Step 5 under Get user details'
4. See typo

### Expected behavior

```py
from tutorial.auth_helper import get_sign_in_flow, get_token_from_code, store_user, remove_user_and_token, get_token
```
### Screenshots

![graph_python_typo](https://user-images.githubusercontent.com/40166690/104441084-4674f680-55a4-11eb-8b5c-d7a2f9c6cbf1.png)

**Comment by jasonjoh** [comment]
Thanks for reporting. This has been fixed (see #46) but hasn't been published to the live site yet.
