### ISSUE TITLE
KeyError at /tutorial/calendar  'value'

### ISSUE THREAD

**Issue by msterzhang** [microsoftgraph/msgraph-training-pythondjangoapp#5]
### Hi. Thank you very much for your work.

In the use of the program, I encountered a problem, I have successfully logged in, but when I get calendar information, I received such an error.

`Internal Server Error: /tutorial/calendar
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\python\django项目\Github网站\graph_tutorial\tutorial\views.py", line 66, in calendar
    for event in events['value']:
KeyError: 'value'`

I printed token and got the following
`{'token_type': 'Bearer', 'scope': ['Calendars.Read', 'openid', 'profile', 'User.Read', 'email'], 'expires_in': 3599, '`

![image](https://user-images.githubusercontent.com/31364579/49928283-d4301480-fefa-11e8-9f7f-08c8e6799cfc.png)
I found that I should not have permissions, so I opened it in the application settings, but when I logged in from the new time, he still did not get these permissions; so where should I open it? Thank you

**Comment by jasonjoh** [comment]
As you've said, your token has `Calendars.Read`, so you have the appropriate permissions. This sample will not use any permissions you've set on the registration, as it requests only specific permissions during the authentication/authorization phase. 

https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/785700936fc60bd3fdbe1a77f75ff48d82672b16/Demos/03-add-msgraph/graph_tutorial/oauth_settings.yml.example#L4

It would be more informative to see exactly what the response is when you get this error. You might try inspecting the `events` variable here:

https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/785700936fc60bd3fdbe1a77f75ff48d82672b16/Demos/03-add-msgraph/graph_tutorial/tutorial/views.py#L61

**Comment by jasonjoh** [comment]
The `Resource could not be discovered` error indicates there is a problem locating either your mailbox or your calendar. Can you try going to the [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) and trying API calls with your account?

**Comment by jasonjoh** [comment]
Closing this issue since I haven't heard back.
