### ISSUE TITLE
Syntax Error on Raise From in Manage.py because of the shebang line?

### ISSUE THREAD

**Issue by cwoodybutler** [microsoftgraph/msgraph-training-pythondjangoapp#50]
I'm getting a syntax error on the raise ImportError line in manage.py because of the shebang line

File ".\manage.py", line 12
    raise ImportError("Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?" ) from exc

I messed a bit with the error line while I was trying to figure out what was wrong. 

If I remove 
#!/usr/bin/env python
 it doesn't seem to get a syntax error.

Help?

**Comment by jasonjoh** [comment]
manage.py is created by Django when you first create the project. If you downloaded this project, you'll need to run a `pip install -r requirements.txt`, which should install Django and the other dependencies for you.

**Comment by cwoodybutler** [comment]
I did do the pip install part, it's a syntax error on the code, it's not throwing an error. Or at least I'm pretty sure it's a syntax error. :)

**Comment by jasonjoh** [comment]
It's generated code though! :D I don't think changing it is the way to go, it may cause you issues down the road.

From what I see online, the error tends to point to how you have Python installed (multiple Python versions, virtual environments, etc.). For example: https://stackoverflow.com/questions/46210934/importerror-couldnt-import-django

It could also be related to the scope where you install Django. The instructions have you install it in the user scope. Try this to see if you get the same error.

In an empty directory:

```
pip install --user Django==3.1.4
django-admin startproject graph_tutorial
python manage.py runserver
```

Does the app start and can you browse to the welcome page at http://localhost:8000?

**Comment by cwoodybutler** [comment]
I figured it out - I had like 47 different versions of python installed, and apparently it was using an older one. I got rid of all older ones and it seems like it's OK now. Der, sorry.
