### ISSUE TITLE
settings.py needs to be updated for templates and static folders

### ISSUE THREAD

**Issue by natisdale** [microsoftgraph/msgraph-training-pythondjangoapp#51]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [X] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Tutorial creates the folders `tutorial/templates/tutorial` and `tutorial/static/tutorial`.  Instructions for updating settings.py to see content placed in these folders is not included in tutorial steps.  This could prevent someone who is new to Django from being able to complete the tutorial.

### To Reproduce

Follow the first section of the tutorial, 'Create a Python Django Web App'

### Expected behavior

Expected home page to load.

### Screenshots

django.template.exceptions.TemplateDoesNotExist

### Desktop

- OS: MacOS
- Browser edge, Firefox, safari
- Version 11.2.1

### Dependency versions

- Authentication library (MSAL, etc.) version: 1.7.0
- Graph library (Graph SDK, REST library, etc.) version:

### Additional context

The following settings will resolve the TemplateDoesNotExist issue:

        TEMPLATES = [
            {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [(BASE_DIR / 'tutorial/templates/'),],
                'APP_DIRS': True,
                'OPTIONS': {
                    'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                    ],
                },
            },
        ]
        
        STATICFILES_DIRS = [
            (BASE_DIR / "tutorial/static/"),
        ]

**Comment by jasonjoh** [comment]
Interesting. This may be a change to Django. I did not have to modify settings.py this way. I took a look at their documentation and don't see anything about a change here though.

From https://docs.djangoproject.com/en/3.1/intro/tutorial03/#write-views-that-actually-do-something, it looks like you shouldn't have to do this:

> Your project’s TEMPLATES setting describes how Django will load and render templates. The default settings file configures a DjangoTemplates backend whose APP_DIRS option is set to True. By convention DjangoTemplates looks for a “templates” subdirectory in each of the INSTALLED_APPS.
>
> Within the templates directory you have just created, create another directory called polls, and within that create a file called index.html. In other words, your template should be at polls/templates/polls/index.html. Because of how the app_directories template loader works as described above, you can refer to this template within Django as polls/index.html.

With `'APP_DIRS': True`, the app should work, since the directory structure is following the `app_name/templates/app_name` convention. What version of Django are you using?

**Comment by natisdale** [comment]
Django==3.1.4

**Comment by jasonjoh** [comment]
Interesting. I have 3.1.4 on my machine, but when it generates a project, settings.py still says it was generated by 3.0.4, and it uses the `os.path.dirname` approach. It looks like I've got an issue with multiple Python versions on this machine. I'll clean that up and get this straightened out in the tutorial. Thanks for reporting.
