### ISSUE TITLE
authority issue needs to be discussed in tutorial

### ISSUE THREAD

**Issue by jmplun** [microsoftgraph/msgraph-training-pythondjangoapp#59]
as part of the tutorial depending on what authority you are using ( personal or consumer) you may need to change the yaml file to suit.. e.g if you are using a personal file you would need to use the consumers authority, prob worth calling out in the tutorial.
![Screen Shot 2021-06-03 at 4 59 20 pm](https://user-images.githubusercontent.com/1401266/120601423-401ce380-c48d-11eb-8d6e-49c2d23b4bf9.png)

**Comment by jasonjoh** [comment]
This is why the tutorial uses the `common` authority URL - it supports both work/school and personal accounts. You would only change it to `consumers` if you wanted to limit support in your app to personal accounts only.
