### ISSUE TITLE
Unauthenticated user cannot access the site.

### ISSUE THREAD

**Issue by Nicko-13** [microsoftgraph/msgraph-training-pythondjangoapp#60]
Thank you for provided tutorial, it is very useful.

I need to enhance the login-only-user permission for my site using the provided sample. 
I have developed the following class for this purpose:

```
class LoginWithAccessTokenMixin:
    """
    Check if user authenticated with access token. If the user is not, redirect to login page.
    """
    login_url = "/"

    def dispatch(self, request, *args, **kwargs):
        """
        Extend behavior of parent class method.

        Try to receive session's access token. If user is authenticated and token exists, display view.
        If token doesnt' exist, function get_token raises IndexError and method redirects user to sign in page.
        """
        try:
            self.access_token = get_token(request)
            return super().dispatch(request, *args, **kwargs)
        except IndexError:
            return HttpResponseRedirect(self.login_url)
```
Now every view in project inherit from this class. From manual testing it looks fine and not authenticated user is redirected to login page of Microsoft. 
Could you, please, advise if it is secure enough or some additional functionality should be implemented?
Thank you in advance.

**Comment by jasonjoh** [comment]
@Nicko-13 sorry for the delay in responding. As you say, the code works. As to if it's "secure enough", only you can make that determination, depending on your requirements and scenario.
