### ISSUE TITLE
Why is pycparser needed?

### ISSUE THREAD

**Issue by jensenbox** [microsoftgraph/msgraph-training-pythondjangoapp#66]
https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/4f7d41c9ccd75ecb80847872dba4393dbb5cfbaa/demo/graph_tutorial/requirements.txt#L9

I cannot seem to find any use of it in the project. Seems a bit weird personally.

**Comment by jasonjoh** [comment]
Thanks for your question! It's not a direct requirement, it must be a dependency of one of Django or one of the [direct dependencies](https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/main/tutorial/02-create-app.md#install-libraries).
