### ISSUE TITLE
Quickstart Fails to Authenticate.

### ISSUE THREAD

**Issue by fatpacket** [microsoftgraph/msgraph-training-pythondjangoapp#79]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ X ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Unable to authenticate against an Azure Tenant - user@<dev-tenant>.onmicrosoft.com
Works fine with personal MS accounts

### To Reproduce

Followed the quickstart and it auto-generated the application and created the Key and Secret in the YML file. Unzipped the file. Created a virtual environment, ran pip install -r requirements.txt to install the version as required. Python manage.py migrate and then python manage.py runserver.
Went directly to the home page http://localhost:8000 and got presented with the branded login screen. Clicked Sign and got redirected to MS Login screen. Entered the username, password got prompted for my MS Authenticator to approve the login. Following the approval, I accepted the application permissions and got redirected back to the home page.  The server console shows the /signin HTTP/1.1 302 0 and following the acceptance of the application permissions I see the console  with the /callback?code=0.AAVAAQCX{....} etc. But i do not see the authenticated Nav Bar items. As a test of my authentication, I went to the /calendar route and it too errored with a  line 75, in calendar    time_zone = get_iana_from_windows(user['timeZone'])  which is unrelated to the auth error.  But the user vars on the debug page show 

{'user': {'is_authenticated': False}} 
request | <WSGIRequest: GET '/calendar'>
user | {'is_authenticated': False}

So I can tell I am not authenticated. I attempted the /signout route and the console reports /signout HTTP/1.1 302 and I am redirected to the default route "/"

This is a Micosoft E5 developer account just created.
SUbsequent requests to not prompt for app permissions but still go through the authenticator but still fail.

(note:  I tried to access the app with my personal MS account not part of the tenant and the app worked as expected)

### Expected behavior

I would expect that when I hit sign in and approve when authenticating against an Azure Tenant the same way it would against a personal account.

### Dependency versions

asgiref==3.3.4
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cryptography==3.4.6
Django==3.2
idna==2.10
msal==1.10.0
pycparser==2.20
PyJWT==2.0.1
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
six==1.15.0
sqlparse==0.4.1
urllib3==1.26.4

### Additional context

The default dev E5 tenant is locked down pretty tight with security by default. I just created this tenant last week.
I also tried to follow the Tutorial and typed all the data in myself but that yielded the same results. I initially though the error was mine but when I downloaded the quickstart and thirdly the git repo and ALL 3 methods produced the same results.  I suspect this is a permission or scope issue

**Comment by fatpacket** [comment]
The permission was not set for MailboxSettings.Read was NOT set in the my new tenant. I sent the permission and then ran the query. Here is the output after I chose consent for that property


    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(mailboxSettings)/$entity",
    "id": "{{ OMITTED }}",
    "mailboxSettings": {
        "archiveFolder": "{{ OMITTED }}",
        "delegateMeetingMessageDeliveryOptions": "sendToDelegateOnly",
        "dateFormat": "",
        "timeFormat": "",
        "userPurpose": "user",
        "automaticRepliesSetting": {
            "status": "disabled",
            "externalAudience": "all",
            "internalReplyMessage": "",
            "externalReplyMessage": "",
            "scheduledStartDateTime": {
                "dateTime": "2022-02-23T05:00:00.0000000",
                "timeZone": "UTC"
            },
            "scheduledEndDateTime": {
                "dateTime": "2022-02-24T05:00:00.0000000",
                "timeZone": "UTC"
            }
        },
        "language": {},
        "workingHours": {}
    }
}

**Comment by jasonjoh** [comment]
Ok yes you are hitting this issue. The `timeZone` property is missing. You can fix it by going into your Outlook settings (at outlook.office.com) and viewing or setting your timezone.

This code is intended to use `UTC` if the property is missing in the Graph response.

https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/17d1d48cea829761546cea8efd8f7c33752376b3/demo/graph_tutorial/tutorial/auth_helper.py#L66

I think I may have the syntax wrong. Can you try changing it to:

```python
'timeZone': user['mailboxSettings']['timeZone'] if (user['mailboxSettings']['timeZone'] is not None) else 'UTC'
```

**Comment by fatpacket** [comment]
I made the requested change
'timeZone': user['mailboxSettings']['timeZone'] if (user['mailboxSettings']['timeZone'] is not None) else 'UTC'
But I am still unable to authenticate unless I am using my person account.  The auth against the tenant still returns to the home page with the exact same behavior as above.

I started this project with a free gmail account, then signed up for a developer account E5 subscription for 90 day. I logged into the portal with my newly provisioned tenant information and ran this code sample.  Nothing else.  I wonder or maybe you know if the default developer tenant is not locked down so much it wont let the registered app work.

**Comment by jasonjoh** [comment]
To my knowledge, not it is not.

Can you try the workaround of ensuring your time zone is set in outlook.office.com for your account?

![image](https://user-images.githubusercontent.com/8966342/155405511-0a34d96b-194b-49d1-9f7b-bb98fc7ace94.png)

**Comment by fatpacket** [comment]
Having a TZ specified in the code fixed the issue.  I am successfully logged in.

**Comment by jasonjoh** [comment]
Thanks for confirming. So basically the auth flow was working the whole time, it's the app that was failing to store the user in the session due to the null time zone value.

**Comment by jasonjoh** [comment]
I was able to find a user that could reproduce this, fix incoming.
